// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { JoinRoom } from "./join_room_type";
import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `join_room`.
 *
 * Obtain a handle from the [`joinRoom`] property on [`RemoteTables`],
 * like `ctx.db.joinRoom`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.joinRoom.on_insert(...)`.
 */
export class JoinRoomTableHandle {
  tableCache: TableCache<JoinRoom>;

  constructor(tableCache: TableCache<JoinRoom>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<JoinRoom> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `room_id` unique index on the table `join_room`,
   * which allows point queries on the field of the same name
   * via the [`JoinRoomRoomIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.joinRoom.room_id().find(...)`.
   *
   * Get a handle on the `room_id` unique index on the table `join_room`.
   */
  room_id = {
    // Find the subscribed row whose `room_id` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): JoinRoom | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.room_id, col_val)) {
          return row;
        }
      }
    },
  };
  /**
   * Access to the `joiner` unique index on the table `join_room`,
   * which allows point queries on the field of the same name
   * via the [`JoinRoomJoinerUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.joinRoom.joiner().find(...)`.
   *
   * Get a handle on the `joiner` unique index on the table `join_room`.
   */
  joiner = {
    // Find the subscribed row whose `joiner` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: Identity): JoinRoom | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.joiner, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: JoinRoom) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: JoinRoom) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: JoinRoom) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: JoinRoom) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }
}
