// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type JoinRoom = {
  roomId: number,
  joinerId: number,
  joinerIdentity: Identity,
  isOwner: boolean,
  joinedAt: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace JoinRoom {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("roomId", AlgebraicType.createU32Type()),
      new ProductTypeElement("joinerId", AlgebraicType.createU32Type()),
      new ProductTypeElement("joinerIdentity", AlgebraicType.createIdentityType()),
      new ProductTypeElement("isOwner", AlgebraicType.createBoolType()),
      new ProductTypeElement("joinedAt", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: JoinRoom): void {
    JoinRoom.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): JoinRoom {
    return JoinRoom.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


